version: "3.9"

services:
  meteo-app:
    build: .
    ports:
      - "8080:8080"
    container_name: meteo-app
    volumes:
      - ./target:/app/target  # Monta la cartella target
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m  # Opzionale: ottimizzazione memoria
